
services:

  nifi:
    image: apache/nifi:1.11.4
    container_name: nifi
    ports:
      - "9090:9090"
    environment:
      - NIFI_WEB_HTTP_PORT=9090
      - NIFI_CLUSTER_IS_NODE=false
   # volumes:
   #   - ${DATADIR}/nifi_data:/home/nifi/data
    networks:
      - nova-intermedio

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks: 
      - nova-intermedio

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka
    networks: 
      - nova-intermedio
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  nova-intermedio:
    external:
      name: nova-intermedio